{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "e0c4c38d",
   "metadata": {},
   "outputs": [],
   "source": [
    "# multi-class classification with Keras\n",
    "import pandas as pd\n",
    "import keras\n",
    "import numpy as np\n",
    "import seaborn as sns\n",
    "import sklearn\n",
    "from keras.models import Sequential\n",
    "from keras.layers import Dense\n",
    "from keras.wrappers.scikit_learn import KerasClassifier\n",
    "from keras.utils import np_utils\n",
    "from sklearn.preprocessing import MinMaxScaler\n",
    "from sklearn.model_selection import cross_val_score\n",
    "from sklearn.model_selection import KFold\n",
    "from sklearn.preprocessing import LabelEncoder\n",
    "from sklearn.pipeline import Pipeline\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 43,
   "id": "83393984",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[['Area' 'Perimeter' 'MajorAxisLength' ... 'ShapeFactor3' 'ShapeFactor4'\n",
      "  'Class']\n",
      " ['44830' '814.955' '320.731946763988' ... '0.554874053004642'\n",
      "  '0.9975336999649' 'SIRA']\n",
      " ['33476' '691.826' '258.837970920502' ... '0.636191268868057'\n",
      "  '0.996669287144026' 'DERMASON']\n",
      " ...\n",
      " ['48266' '817.34' '304.682706035489' ... '0.661996691510444'\n",
      "  '0.99711663035426' 'SIRA']\n",
      " ['43279' '843.066' '336.280445730313' ... '0.487286194409708'\n",
      "  '0.995127649215058' 'HOROZ']\n",
      " ['46856' '809.173' '302.595376396372' ... '0.651554508177527'\n",
      "  '0.996145309812014' 'SIRA']]\n"
     ]
    },
    {
     "ename": "ValueError",
     "evalue": "No variables found for grid columns.",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mValueError\u001b[0m                                Traceback (most recent call last)",
      "\u001b[1;32m~\\AppData\\Local\\Temp/ipykernel_12428/2938807383.py\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      4\u001b[0m \u001b[1;31m# Drop all rows containing NaN values from the data frame\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m      5\u001b[0m \u001b[0mdataframe\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mdropna\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0minplace\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mTrue\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m----> 6\u001b[1;33m \u001b[0msns\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mpairplot\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mdataframe\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mhue\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m'Class'\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[1;32m~\\.conda\\envs\\keras_env\\lib\\site-packages\\seaborn\\_decorators.py\u001b[0m in \u001b[0;36minner_f\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     44\u001b[0m             )\n\u001b[0;32m     45\u001b[0m         \u001b[0mkwargs\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mupdate\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m{\u001b[0m\u001b[0mk\u001b[0m\u001b[1;33m:\u001b[0m \u001b[0marg\u001b[0m \u001b[1;32mfor\u001b[0m \u001b[0mk\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0marg\u001b[0m \u001b[1;32min\u001b[0m \u001b[0mzip\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0msig\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mparameters\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0margs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m}\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 46\u001b[1;33m         \u001b[1;32mreturn\u001b[0m \u001b[0mf\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     47\u001b[0m     \u001b[1;32mreturn\u001b[0m \u001b[0minner_f\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     48\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\keras_env\\lib\\site-packages\\seaborn\\axisgrid.py\u001b[0m in \u001b[0;36mpairplot\u001b[1;34m(data, hue, hue_order, palette, vars, x_vars, y_vars, kind, diag_kind, markers, height, aspect, corner, dropna, plot_kws, diag_kws, grid_kws, size)\u001b[0m\n\u001b[0;32m   2094\u001b[0m     \u001b[1;31m# Set up the PairGrid\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   2095\u001b[0m     \u001b[0mgrid_kws\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0msetdefault\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"diag_sharey\"\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mdiag_kind\u001b[0m \u001b[1;33m==\u001b[0m \u001b[1;34m\"hist\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 2096\u001b[1;33m     grid = PairGrid(data, vars=vars, x_vars=x_vars, y_vars=y_vars, hue=hue,\n\u001b[0m\u001b[0;32m   2097\u001b[0m                     \u001b[0mhue_order\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mhue_order\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mpalette\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mpalette\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mcorner\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mcorner\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   2098\u001b[0m                     height=height, aspect=aspect, dropna=dropna, **grid_kws)\n",
      "\u001b[1;32m~\\.conda\\envs\\keras_env\\lib\\site-packages\\seaborn\\_decorators.py\u001b[0m in \u001b[0;36minner_f\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     44\u001b[0m             )\n\u001b[0;32m     45\u001b[0m         \u001b[0mkwargs\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mupdate\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m{\u001b[0m\u001b[0mk\u001b[0m\u001b[1;33m:\u001b[0m \u001b[0marg\u001b[0m \u001b[1;32mfor\u001b[0m \u001b[0mk\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0marg\u001b[0m \u001b[1;32min\u001b[0m \u001b[0mzip\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0msig\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mparameters\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0margs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m}\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 46\u001b[1;33m         \u001b[1;32mreturn\u001b[0m \u001b[0mf\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     47\u001b[0m     \u001b[1;32mreturn\u001b[0m \u001b[0minner_f\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     48\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32m~\\.conda\\envs\\keras_env\\lib\\site-packages\\seaborn\\axisgrid.py\u001b[0m in \u001b[0;36m__init__\u001b[1;34m(self, data, hue, hue_order, palette, hue_kws, vars, x_vars, y_vars, corner, diag_sharey, height, aspect, layout_pad, despine, dropna, size)\u001b[0m\n\u001b[0;32m   1231\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1232\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[0mx_vars\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1233\u001b[1;33m             \u001b[1;32mraise\u001b[0m \u001b[0mValueError\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"No variables found for grid columns.\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1234\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[0my_vars\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m   1235\u001b[0m             \u001b[1;32mraise\u001b[0m \u001b[0mValueError\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"No variables found for grid rows.\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mValueError\u001b[0m: No variables found for grid columns."
     ]
    }
   ],
   "source": [
    "dataframe = pd.read_csv(\"Dry_Beans_Dataset.csv\", header=None)\n",
    "dataset = dataframe.values\n",
    "print(dataset)\n",
    "# Drop all rows containing NaN values from the data frame\n",
    "dataframe.dropna(inplace=True)\n",
    "sns.pairplot(dataframe, hue='Class')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "68827374",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[[44830 814.955 320.731946763988 ... 0.554874053004642 0.9975336999649\n",
      "  'SIRA']\n",
      " [33476 691.826 258.837970920502 ... 0.636191268868057 0.996669287144026\n",
      "  'DERMASON']\n",
      " [27057 606.138 227.460904061774 ... 0.665849745943662 0.997329554413052\n",
      "  'DERMASON']\n",
      " ...\n",
      " [48266 817.34 304.682706035489 ... 0.661996691510444 0.99711663035426\n",
      "  'SIRA']\n",
      " [43279 843.066 336.280445730313 ... 0.487286194409708 0.995127649215058\n",
      "  'HOROZ']\n",
      " [46856 809.173 302.595376396372 ... 0.651554508177527 0.996145309812014\n",
      "  'SIRA']]\n",
      "Original X data set\n",
      "[[4.48300000e+04 8.14955000e+02 3.20731947e+02 ... 1.35875789e-03\n",
      "  5.54874053e-01 9.97533700e-01]\n",
      " [3.34760000e+04 6.91826000e+02 2.58837971e+02 ... 1.93041018e-03\n",
      "  6.36191269e-01 9.96669287e-01]\n",
      " [2.70570000e+04 6.06138000e+02 2.27460904e+02 ... 2.29910793e-03\n",
      "  6.65849746e-01 9.97329554e-01]\n",
      " ...\n",
      " [4.82660000e+04 8.17340000e+02 3.04682706e+02 ... 1.70646701e-03\n",
      "  6.61996692e-01 9.97116630e-01]\n",
      " [4.32790000e+04 8.43066000e+02 3.36280446e+02 ... 1.13807891e-03\n",
      "  4.87286194e-01 9.95127649e-01]\n",
      " [4.68560000e+04 8.09173000e+02 3.02595376e+02 ... 1.69113527e-03\n",
      "  6.51554508e-01 9.96145310e-01]]\n",
      "Original Y data set\n",
      "[['SIRA']\n",
      " ['DERMASON']\n",
      " ['DERMASON']\n",
      " ...\n",
      " ['SIRA']\n",
      " ['HOROZ']\n",
      " ['SIRA']]\n",
      "Original Y data set - Post ravel - convert the format to simple array\n",
      "['SIRA' 'DERMASON' 'DERMASON' ... 'SIRA' 'HOROZ' 'SIRA']\n",
      "Preform MinMaxScaler on X\n",
      "[[4.48300000e+04 8.14955000e+02 3.20731947e+02 ... 1.35875789e-03\n",
      "  5.54874053e-01 9.97533700e-01]\n",
      " [3.34760000e+04 6.91826000e+02 2.58837971e+02 ... 1.93041018e-03\n",
      "  6.36191269e-01 9.96669287e-01]\n",
      " [2.70570000e+04 6.06138000e+02 2.27460904e+02 ... 2.29910793e-03\n",
      "  6.65849746e-01 9.97329554e-01]\n",
      " ...\n",
      " [4.82660000e+04 8.17340000e+02 3.04682706e+02 ... 1.70646701e-03\n",
      "  6.61996692e-01 9.97116630e-01]\n",
      " [4.32790000e+04 8.43066000e+02 3.36280446e+02 ... 1.13807891e-03\n",
      "  4.87286194e-01 9.95127649e-01]\n",
      " [4.68560000e+04 8.09173000e+02 3.02595376e+02 ... 1.69113527e-03\n",
      "  6.51554508e-01 9.96145310e-01]]\n",
      "Convert class to one-hot encoding\n",
      "hot encoded Y\n",
      "[[0. 0. 0. ... 0. 0. 1.]\n",
      " [0. 0. 0. ... 0. 0. 0.]\n",
      " [0. 0. 0. ... 0. 0. 0.]\n",
      " ...\n",
      " [0. 0. 0. ... 0. 0. 1.]\n",
      " [0. 0. 0. ... 1. 0. 0.]\n",
      " [0. 0. 0. ... 0. 0. 1.]]\n"
     ]
    }
   ],
   "source": [
    "\n",
    "# load dataset\n",
    "# loading dataset using seaborn\n",
    "dataframe = pd.read_csv(\"Dry_Beans_Dataset.csv\")\n",
    "dataset = dataframe.values\n",
    "print(dataset)\n",
    "sns.pairplot(dataframe, hue='class')\n",
    "X = dataset[:,:-1].astype(float)\n",
    "Y = dataset[:,-1:]\n",
    "print('Original X data set')\n",
    "print(X)\n",
    "print('Original Y data set')\n",
    "print(Y)\n",
    "Y = np.ravel(Y) # convert the format to simple array\n",
    "print('Original Y data set - Post ravel - convert the format to simple array')\n",
    "print(Y)\n",
    "\n",
    "print('Preform MinMaxScaler on X')\n",
    "scaler = MinMaxScaler()\n",
    "scaler.fit_transform(X)\n",
    "print(X)\n",
    "\n",
    "print('Convert class to one-hot encoding')\n",
    "# encode class values as integers\n",
    "encoder = LabelEncoder()\n",
    "encoder.fit(Y)\n",
    "encoded_Y = encoder.transform(Y)\n",
    "# convert integers to one hot encoded\n",
    "y = np_utils.to_categorical(encoded_Y, num_classes=None, dtype=\"float32\")\n",
    "print('hot encoded Y')\n",
    "print(y)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 42,
   "id": "30030702",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Area</th>\n",
       "      <th>Perimeter</th>\n",
       "      <th>MajorAxisLength</th>\n",
       "      <th>MinorAxisLength</th>\n",
       "      <th>AspectRation</th>\n",
       "      <th>Eccentricity</th>\n",
       "      <th>ConvexArea</th>\n",
       "      <th>EquivDiameter</th>\n",
       "      <th>Extent</th>\n",
       "      <th>Solidity</th>\n",
       "      <th>roundness</th>\n",
       "      <th>Compactness</th>\n",
       "      <th>ShapeFactor1</th>\n",
       "      <th>ShapeFactor2</th>\n",
       "      <th>ShapeFactor3</th>\n",
       "      <th>ShapeFactor4</th>\n",
       "      <th>Class</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>44830</td>\n",
       "      <td>814.955</td>\n",
       "      <td>320.731947</td>\n",
       "      <td>178.405838</td>\n",
       "      <td>1.797766</td>\n",
       "      <td>0.831018</td>\n",
       "      <td>45297</td>\n",
       "      <td>238.912806</td>\n",
       "      <td>0.658877</td>\n",
       "      <td>0.989690</td>\n",
       "      <td>0.848226</td>\n",
       "      <td>0.744899</td>\n",
       "      <td>0.007154</td>\n",
       "      <td>0.001359</td>\n",
       "      <td>0.554874</td>\n",
       "      <td>0.997534</td>\n",
       "      <td>SIRA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>33476</td>\n",
       "      <td>691.826</td>\n",
       "      <td>258.837971</td>\n",
       "      <td>165.220760</td>\n",
       "      <td>1.566619</td>\n",
       "      <td>0.769773</td>\n",
       "      <td>33907</td>\n",
       "      <td>206.453305</td>\n",
       "      <td>0.721155</td>\n",
       "      <td>0.987289</td>\n",
       "      <td>0.878921</td>\n",
       "      <td>0.797616</td>\n",
       "      <td>0.007732</td>\n",
       "      <td>0.001930</td>\n",
       "      <td>0.636191</td>\n",
       "      <td>0.996669</td>\n",
       "      <td>DERMASON</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>27057</td>\n",
       "      <td>606.138</td>\n",
       "      <td>227.460904</td>\n",
       "      <td>151.860320</td>\n",
       "      <td>1.497830</td>\n",
       "      <td>0.744491</td>\n",
       "      <td>27358</td>\n",
       "      <td>185.607226</td>\n",
       "      <td>0.801831</td>\n",
       "      <td>0.988998</td>\n",
       "      <td>0.925436</td>\n",
       "      <td>0.815996</td>\n",
       "      <td>0.008407</td>\n",
       "      <td>0.002299</td>\n",
       "      <td>0.665850</td>\n",
       "      <td>0.997330</td>\n",
       "      <td>DERMASON</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>49483</td>\n",
       "      <td>844.283</td>\n",
       "      <td>326.602913</td>\n",
       "      <td>194.689529</td>\n",
       "      <td>1.677558</td>\n",
       "      <td>0.802907</td>\n",
       "      <td>50289</td>\n",
       "      <td>251.005403</td>\n",
       "      <td>0.680179</td>\n",
       "      <td>0.983973</td>\n",
       "      <td>0.872348</td>\n",
       "      <td>0.768534</td>\n",
       "      <td>0.006600</td>\n",
       "      <td>0.001420</td>\n",
       "      <td>0.590644</td>\n",
       "      <td>0.990840</td>\n",
       "      <td>SIRA</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>22461</td>\n",
       "      <td>544.584</td>\n",
       "      <td>192.801303</td>\n",
       "      <td>148.541136</td>\n",
       "      <td>1.297966</td>\n",
       "      <td>0.637517</td>\n",
       "      <td>22699</td>\n",
       "      <td>169.110122</td>\n",
       "      <td>0.774731</td>\n",
       "      <td>0.989515</td>\n",
       "      <td>0.951720</td>\n",
       "      <td>0.877121</td>\n",
       "      <td>0.008584</td>\n",
       "      <td>0.003134</td>\n",
       "      <td>0.769342</td>\n",
       "      <td>0.998579</td>\n",
       "      <td>DERMASON</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    Area  Perimeter  MajorAxisLength  MinorAxisLength  AspectRation  \\\n",
       "0  44830    814.955       320.731947       178.405838      1.797766   \n",
       "1  33476    691.826       258.837971       165.220760      1.566619   \n",
       "2  27057    606.138       227.460904       151.860320      1.497830   \n",
       "3  49483    844.283       326.602913       194.689529      1.677558   \n",
       "4  22461    544.584       192.801303       148.541136      1.297966   \n",
       "\n",
       "   Eccentricity  ConvexArea  EquivDiameter    Extent  Solidity  roundness  \\\n",
       "0      0.831018       45297     238.912806  0.658877  0.989690   0.848226   \n",
       "1      0.769773       33907     206.453305  0.721155  0.987289   0.878921   \n",
       "2      0.744491       27358     185.607226  0.801831  0.988998   0.925436   \n",
       "3      0.802907       50289     251.005403  0.680179  0.983973   0.872348   \n",
       "4      0.637517       22699     169.110122  0.774731  0.989515   0.951720   \n",
       "\n",
       "   Compactness  ShapeFactor1  ShapeFactor2  ShapeFactor3  ShapeFactor4  \\\n",
       "0     0.744899      0.007154      0.001359      0.554874      0.997534   \n",
       "1     0.797616      0.007732      0.001930      0.636191      0.996669   \n",
       "2     0.815996      0.008407      0.002299      0.665850      0.997330   \n",
       "3     0.768534      0.006600      0.001420      0.590644      0.990840   \n",
       "4     0.877121      0.008584      0.003134      0.769342      0.998579   \n",
       "\n",
       "      Class  \n",
       "0      SIRA  \n",
       "1  DERMASON  \n",
       "2  DERMASON  \n",
       "3      SIRA  \n",
       "4  DERMASON  "
      ]
     },
     "execution_count": 42,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#========= ML - HW 2 By Ofek Marom ==========\n",
    "\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "from IPython.display import Image\n",
    "\n",
    "df = pd.read_csv(\"Dry_Beans_Dataset.csv\") #df = pd.read_csv(\"Dry_Beans_Dataset.csv\", header=None)\n",
    "df.head(5)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "61d43510",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Drop all rows containing NaN values from the data frame\n",
    "df.dropna(inplace=True)\n",
    "sns.pairplot(df, hue='Class')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b848b05b",
   "metadata": {},
   "outputs": [],
   "source": [
    "from sklearn import preprocessing\n",
    "from sklearn.preprocessing import MinMaxScaler\n",
    "from sklearn.model_selection import train_test_split\n",
    "train, test = train_test_split(df, test_size=0.1, random_state=21)\n",
    "\n",
    "X_train, y_train = train.drop(columns=['Class']), train['Class']\n",
    "X_test, y_test = test.drop(columns=['Class']), test['Class']\n",
    "\n",
    "#scaler = preprocessing.StandardScaler()\n",
    "scaler = MinMaxScaler() # replace StandardScaler with other scalings such as MinMaxScaler()\n",
    "scaler.fit(X_train)\n",
    "X_train = scaler.transform(X_train)\n",
    "X_test = scaler.transform(X_test)\n",
    "\n",
    "print(X_train.shape, X_test.shape)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "3b3127e7",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py\", line 1184, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 885, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 759, in _initialize\n",
      "    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3066, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3463, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3298, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1007, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 668, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 994, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:853 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:842 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1286 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2849 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:3632 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:835 run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:787 train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\base_layer.py:1020 __call__\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\input_spec.py:250 assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_10 is incompatible with the layer: expected axis -1 of input shape to have value 4 but received input with shape (None, 16)\n",
      "\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py\", line 1184, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 885, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 759, in _initialize\n",
      "    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3066, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3463, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3298, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1007, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 668, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 994, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:853 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:842 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1286 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2849 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:3632 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:835 run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:787 train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\base_layer.py:1020 __call__\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\input_spec.py:250 assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_11 is incompatible with the layer: expected axis -1 of input shape to have value 4 but received input with shape (5, 16)\n",
      "\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py\", line 1184, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 885, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 759, in _initialize\n",
      "    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3066, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3463, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3298, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1007, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 668, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 994, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:853 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:842 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1286 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2849 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:3632 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:835 run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:787 train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\base_layer.py:1020 __call__\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\input_spec.py:250 assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_12 is incompatible with the layer: expected axis -1 of input shape to have value 4 but received input with shape (5, 16)\n",
      "\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py\", line 1184, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 885, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 759, in _initialize\n",
      "    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3066, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3463, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3298, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1007, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 668, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 994, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:853 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:842 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1286 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2849 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:3632 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:835 run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:787 train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\base_layer.py:1020 __call__\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\input_spec.py:250 assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_13 is incompatible with the layer: expected axis -1 of input shape to have value 4 but received input with shape (5, 16)\n",
      "\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py\", line 1184, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 885, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 759, in _initialize\n",
      "    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3066, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3463, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3298, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1007, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 668, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 994, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:853 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:842 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1286 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2849 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:3632 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:835 run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:787 train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\base_layer.py:1020 __call__\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\input_spec.py:250 assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_14 is incompatible with the layer: expected axis -1 of input shape to have value 4 but received input with shape (5, 16)\n",
      "\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py\", line 1184, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 885, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 759, in _initialize\n",
      "    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3066, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3463, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3298, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1007, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 668, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 994, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:853 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:842 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1286 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2849 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:3632 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:835 run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:787 train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\base_layer.py:1020 __call__\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\input_spec.py:250 assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_15 is incompatible with the layer: expected axis -1 of input shape to have value 4 but received input with shape (5, 16)\n",
      "\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py\", line 1184, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 885, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 759, in _initialize\n",
      "    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3066, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3463, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3298, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1007, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 668, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 994, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:853 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:842 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1286 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2849 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:3632 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:835 run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:787 train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\base_layer.py:1020 __call__\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\input_spec.py:250 assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_16 is incompatible with the layer: expected axis -1 of input shape to have value 4 but received input with shape (5, 16)\n",
      "\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py\", line 1184, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 885, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 759, in _initialize\n",
      "    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3066, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3463, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3298, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1007, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 668, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 994, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:853 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:842 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1286 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2849 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:3632 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:835 run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:787 train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\base_layer.py:1020 __call__\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\input_spec.py:250 assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_17 is incompatible with the layer: expected axis -1 of input shape to have value 4 but received input with shape (5, 16)\n",
      "\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Baseline: nan% (nan%)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py\", line 1184, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 885, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 759, in _initialize\n",
      "    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3066, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3463, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3298, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1007, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 668, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 994, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:853 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:842 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1286 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2849 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:3632 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:835 run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:787 train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\base_layer.py:1020 __call__\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\input_spec.py:250 assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_18 is incompatible with the layer: expected axis -1 of input shape to have value 4 but received input with shape (5, 16)\n",
      "\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n",
      "C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\sklearn\\model_selection\\_validation.py:615: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: \n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\sklearn\\model_selection\\_validation.py\", line 598, in _fit_and_score\n",
      "    estimator.fit(X_train, y_train, **fit_params)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 219, in fit\n",
      "    return super(KerasClassifier, self).fit(x, y, **kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\wrappers\\scikit_learn.py\", line 162, in fit\n",
      "    history = self.model.fit(x, y, **fit_args)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py\", line 1184, in fit\n",
      "    tmp_logs = self.train_function(iterator)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 885, in __call__\n",
      "    result = self._call(*args, **kwds)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 933, in _call\n",
      "    self._initialize(args, kwds, add_initializers_to=initializers)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 759, in _initialize\n",
      "    self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3066, in _get_concrete_function_internal_garbage_collected\n",
      "    graph_function, _ = self._maybe_define_function(args, kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3463, in _maybe_define_function\n",
      "    graph_function = self._create_graph_function(args, kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3298, in _create_graph_function\n",
      "    func_graph_module.func_graph_from_py_func(\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1007, in func_graph_from_py_func\n",
      "    func_outputs = python_func(*func_args, **func_kwargs)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 668, in wrapped_fn\n",
      "    out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n",
      "  File \"C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 994, in wrapper\n",
      "    raise e.ag_error_metadata.to_exception(e)\n",
      "ValueError: in user code:\n",
      "\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:853 train_function  *\n",
      "        return step_function(self, iterator)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:842 step_function  **\n",
      "        outputs = model.distribute_strategy.run(run_step, args=(data,))\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:1286 run\n",
      "        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:2849 call_for_each_replica\n",
      "        return self._call_for_each_replica(fn, args, kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py:3632 _call_for_each_replica\n",
      "        return fn(*args, **kwargs)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:835 run_step  **\n",
      "        outputs = model.train_step(data)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\training.py:787 train_step\n",
      "        y_pred = self(x, training=True)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\base_layer.py:1020 __call__\n",
      "        input_spec.assert_input_compatibility(self.input_spec, inputs, self.name)\n",
      "    C:\\Users\\dev_t470\\.conda\\envs\\keras_env\\lib\\site-packages\\keras\\engine\\input_spec.py:250 assert_input_compatibility\n",
      "        raise ValueError(\n",
      "\n",
      "    ValueError: Input 0 of layer sequential_19 is incompatible with the layer: expected axis -1 of input shape to have value 4 but received input with shape (5, 16)\n",
      "\n",
      "\n",
      "  warnings.warn(\"Estimator fit failed. The score on this train-test\"\n"
     ]
    }
   ],
   "source": [
    "# define baseline model\n",
    "def baseline_model():\n",
    "\t# create model\n",
    "\tmodel = Sequential()\n",
    "\tmodel.add(Dense(8, input_dim=4, activation='sigmoid'))\n",
    "\tmodel.add(Dense(3, activation='sigmoid'))\n",
    "\t# Compile model\n",
    "\tmodel.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])\n",
    "\treturn model\n",
    " \n",
    "estimator = KerasClassifier(build_fn=baseline_model, epochs=500, batch_size=5, verbose=0)\n",
    "kfold = KFold(n_splits=10, shuffle=True)\n",
    "results = cross_val_score(estimator, X, y, cv=kfold)\n",
    "print(\"Baseline: %.2f%% (%.2f%%)\" % (results.mean()*100, results.std()*100))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "521735f7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
